#!/usr/bin/env node
/**
 * Reads src/data/*.json and writes database/ingest/ingest.sql.
 * Run whenever the JSON files are updated:
 *
 *   node database/ingest/generate-sql.mjs
 *   wrangler d1 execute dgenesisinfo --file=database/ingest/ingest.sql
 *
 * For local dev:
 *   wrangler d1 execute dgenesisinfo --local --file=database/ingest/ingest.sql
 *
 * The output is fully idempotent — re-running replaces all data cleanly.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const root  = resolve(__dir, '../..');

const characters = JSON.parse(readFileSync(resolve(root, 'src/data/characters.json'), 'utf8'));
const orbs       = JSON.parse(readFileSync(resolve(root, 'src/data/orbs.json'),       'utf8'));
const timeline   = JSON.parse(readFileSync(resolve(root, 'src/data/timeline.json'),   'utf8'));

const lines = [];

const q  = v => v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const qi = v => v == null ? 'NULL' : String(Number(v));
const qr = v => v == null ? 'NULL' : String(Number(v));
const qb = v => v ? '1' : '0';

lines.push('-- Generated by database/ingest/generate-sql.mjs — do not edit by hand.');
lines.push(`-- Generated: ${new Date().toISOString()}`);
lines.push('');
lines.push('PRAGMA foreign_keys = ON;');
lines.push('');

// ─── Orbs ────────────────────────────────────────────────────────────────────

lines.push('-- ── Orbs ───────────────────────────────────────────────────────────────────');
lines.push('DELETE FROM orb_drop_rates;');
lines.push('DELETE FROM orbs;');
lines.push('');

for (const orb of orbs) {
	lines.push(
		`INSERT INTO orbs (slug, orb_id, orb_name, known_effects, note) VALUES (` +
		`${q(orb.slug)}, ${qi(orb.orb_id)}, ${q(orb.orb_name)}, ${q(orb.known_effects)}, ${q(orb.note)});`
	);

	for (const dr of (orb.drop_rates ?? [])) {
		const cite = dr.citation ?? {};
		lines.push(
			`INSERT INTO orb_drop_rates (orb_id, creature, dungeon, floor, favorable_outcomes, total_events, cite_volume, cite_chapter, cite_jnc_part) VALUES (` +
			`(SELECT id FROM orbs WHERE slug = ${q(orb.slug)}), ` +
			`${q(dr.creature)}, ${q(dr.dungeon)}, ${q(dr.floor)}, ` +
			`${qr(dr.favorable_outcomes)}, ${qr(dr.total_events)}, ` +
			`${q(cite.volume)}, ${q(cite.chapter)}, ${q(cite.jnc_part)});`
		);
	}
}

lines.push('');

// ─── Characters ──────────────────────────────────────────────────────────────

lines.push('-- ── Characters ─────────────────────────────────────────────────────────────');
lines.push('DELETE FROM character_orbs;');
lines.push('DELETE FROM character_stats;');
lines.push('DELETE FROM character_rankings;');
lines.push('DELETE FROM characters;');
lines.push('');

for (const char of characters) {
	lines.push(
		`INSERT INTO characters (slug, first_name, last_name, moniker, nationality, date_first_known, is_public, in_wdarl, area, birthday, sex, note, tags) VALUES (` +
		`${q(char.slug)}, ${q(char.first_name)}, ${q(char.last_name)}, ${q(JSON.stringify(char.monikers ?? []))}, ` +
		`${q(char.nationality)}, ${q(char.date_first_known)}, ` +
		`${qb(char.public)}, ${qb(char.in_wdarl)}, ${qi(char.area)}, ` +
		`${q(char.birthday)}, ${q(char.sex)}, ${q(char.note)}, ` +
		`${q(JSON.stringify(char.tags ?? []))});`
	);

	for (const r of (char.rankings ?? [])) {
		const cite = r.citation ?? {};
		lines.push(
			`INSERT INTO character_rankings (character_id, rank, known_above_rank, date_noted, cite_volume, cite_chapter, cite_jnc_part) VALUES (` +
			`(SELECT id FROM characters WHERE slug = ${q(char.slug)}), ` +
			`${qi(r.rank)}, ${qi(r.known_above_rank)}, ${q(r.date_noted)}, ` +
			`${q(cite.volume)}, ${q(cite.chapter)}, ${q(cite.jnc_part)});`
		);
	}

	for (const s of (char.stats ?? [])) {
		const cite = s.citation ?? {};
		lines.push(
			`INSERT INTO character_stats (character_id, date_noted, date_sequence, scan_type, hp, mp, sp, str, vit, int, agi, dex, luc, stat_total, points_from_avg, cite_volume, cite_chapter, cite_jnc_part) VALUES (` +
			`(SELECT id FROM characters WHERE slug = ${q(char.slug)}), ` +
			`${q(s.date_noted)}, ${qi(s.date_sequence)}, ${q(s.scan_type)}, ` +
			`${qr(s.hp)}, ${qr(s.mp)}, ${qr(s.sp)}, ` +
			`${qi(s.str)}, ${qi(s.vit)}, ${qi(s.int)}, ${qi(s.agi)}, ${qi(s.dex)}, ${qi(s.luc)}, ` +
			`${qi(s.stat_total)}, ${qi(s.points_from_average)}, ` +
			`${q(cite.volume)}, ${q(cite.chapter)}, ${q(cite.jnc_part)});`
		);
	}

	for (const ou of (char.orbs_used ?? [])) {
		const cite = ou.citation ?? {};
		lines.push(
			`INSERT INTO character_orbs (character_id, orb_id, date_acquired, date_note, cite_volume, cite_chapter, cite_jnc_part) VALUES (` +
			`(SELECT id FROM characters WHERE slug = ${q(char.slug)}), ` +
			`(SELECT id FROM orbs WHERE orb_id = ${qi(ou.orb_id)}), ` +
			`${q(ou.date_acquired)}, ${q(ou.date_note)}, ` +
			`${q(cite.volume)}, ${q(cite.chapter)}, ${q(cite.jnc_part)});`
		);
	}
}

lines.push('');

// ─── Timeline ────────────────────────────────────────────────────────────────

lines.push('-- ── Timeline ───────────────────────────────────────────────────────────────');
lines.push('DELETE FROM timeline_events;');
lines.push('');

for (const ev of timeline) {
	const cite = ev.citation ?? {};
	lines.push(
		`INSERT INTO timeline_events (date_utc, date_label, display_time, timezone, pre_history, event, cite_volume, cite_chapter, cite_jnc_part) VALUES (` +
		`${q(ev.date_utc)}, ${q(ev.date_label)}, ${qb(ev.display_time)}, ${q(ev.timezone)}, ` +
		`${qb(ev.pre_history)}, ${q(ev.event)}, ` +
		`${q(cite.volume)}, ${q(cite.chapter)}, ${q(cite.jnc_part)});`
	);
}

lines.push('');

const outPath = resolve(__dir, 'ingest.sql');
writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`✓ Wrote ${lines.length} lines to ${outPath}`);
